---
image: docker:latest

variables:
  DOCKER_VERSION: "18.06"
  DOCKER_HOST: tcp://localhost:2375
  CONTAINER_IMAGE: socialgouv/dila2sql
  PREVIOUS_CI_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql_ci:$CI_COMMIT_BEFORE_SHA"
  CI_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql_ci:$CI_COMMIT_SHA"
  PUBLIC_IMAGE_DILA2SQL: "$CI_REGISTRY_IMAGE/dila2sql:$CI_COMMIT_SHA"
  PUBLIC_IMAGE_DILA2SQL_API: "$CI_REGISTRY_IMAGE/dila2sql_api:$CI_COMMIT_SHA"
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  API_PORT: 8080
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - "Prepare"
  - "Run Tests"
  - "Publish Docker images"
  - "Deploy"
  - "Send Url"

###########################################
###               PREPARE               ###
###########################################


#

.build_image_stage: &build_image_stage
  image: docker:$DOCKER_VERSION
  services:
  - docker:dind
  before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN


.save_github_deploy_id_stage: &save_github_deploy_id_stage
  stage: "Prepare"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - envsubst < k8s/scripts/get-deploy-id.sh > k8s/scripts/get-github-deploy-id.sh
  script:
  - sh k8s/scripts/get-github-deploy-id.sh
  artifacts:
    paths:
    - github_deploy_id

#

build-ci-docker-image-dila2sql:
  <<: *build_image_stage
  stage: "Prepare"
  script:
  - docker pull $PREVIOUS_CI_IMAGE_DILA2SQL || true
  - >-
    docker build
    --cache-from $PREVIOUS_CI_IMAGE_DILA2SQL
    -t $CI_IMAGE_DILA2SQL
    packages/dila2sql
  - docker push $CI_IMAGE_DILA2SQL

Save dev github_deploy_id in artifact:
  <<: *save_github_deploy_id_stage
  environment:
    name: dev.factory
  except:
  - ops/deploy-k8s

Save prod github_deploy_id in artifact:
  <<: *save_github_deploy_id_stage
  environment:
    name: incubateur
  only:
  - ops/deploy-k8s

###########################################
###              RUN TESTS              ###
###########################################

run-tests-dila2sql:
  stage: "Run Tests"
  image: docker:$DOCKER_VERSION
  services:
  - docker:dind
  script:
  - docker run -t $CI_IMAGE_DILA2SQL tox

###########################################
###       PUBLISH DOCKER IMAGES         ###
###########################################

Publish docker image dila2sql:
  <<: *build_image_stage
  stage: "Publish Docker images"
  script:
  - docker pull $CI_IMAGE_DILA2SQL || true
  - >-
    docker build
    --cache-from $CI_IMAGE_DILA2SQL
    -t $PUBLIC_IMAGE_DILA2SQL
    packages/dila2sql
  - docker push $PUBLIC_IMAGE_DILA2SQL

Publish docker image dila2sql api:
  <<: *build_image_stage
  stage: "Publish Docker images"
  script:
  - docker pull $PUBLIC_IMAGE_DILA2SQL_API || true
  - >-
    docker build
    --cache-from $PUBLIC_IMAGE_DILA2SQL_API
    -t $PUBLIC_IMAGE_DILA2SQL_API
    packages/api
  - docker push $PUBLIC_IMAGE_DILA2SQL_API

############################################
###                 DEPLOY               ###
############################################

#

.deploy_stage: &deploy_stage
  stage: "Deploy"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  variables:
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
  allow_failure: false

.deploy_dila2sql: &deploy_dila2sql
  script:
  - envsubst < k8s/dila2sql/importer.yml > k8s/dila2sql/importer-dila2sql.yml
  - kubectl apply -f k8s/dila2sql/importer-dila2sql.yml

.deploy_dila2api: &deploy_dila2sql_api
  variables:
    DILA2SQL_API_DB_PORT: $API_PORT
  script:
  - envsubst < k8s/api/deployment.yml > k8s/api/deployment-api.yml
  - envsubst < k8s/api/ingress.yml > k8s/api/ingress-api.yml
  - envsubst < k8s/api/service.yml > k8s/api/service-api.yml
  - kubectl apply -f k8s/api/deployment-api.yml
  - kubectl apply -f k8s/api/ingress-api.yml
  - kubectl apply -f k8s/api/service-api.yml

#

Deploy Postgres to dev environment:
  <<: *deploy_stage
  script:
  - envsubst < k8s/postgres/deployment.yml > k8s/postgres/deployment-postgres.yml
  - envsubst < k8s/postgres/service.yml > k8s/postgres/service-postgres.yml
  - kubectl apply -f k8s/postgres/deployment-postgres.yml
  - kubectl apply -f k8s/postgres/service-postgres.yml
  environment:
    name: dev.factory
  except:
  - ops/deploy-k8s

Deploy dila2sql to dev environment:
  <<: *deploy_stage
  <<: *deploy_dila2sql
  environment:
    name: dev.factory
  except:
  - ops/deploy-k8s

Deploy dila2sql api to dev environment:
  <<: *deploy_stage
  <<: *deploy_dila2sql_api
  environment:
    name: dev.factory
  except:
  - ops/deploy-k8s

Deploy dila2sql to prod environment:
  <<: *deploy_stage
  <<: *deploy_dila2sql
  environment:
    name: incubateur
  only:
  - ops/deploy-k8s

Deploy dila2sql api to prod environment:
  <<: *deploy_stage
  <<: *deploy_dila2sql_api
  script:
  - envsubst < k8s/certificate/certificate.yml > k8s/certificate/certificate-dila2sql.yml
  - kubectl apply -f k8s/certificate/certificate-dila2sql.yml
  environment:
    name: incubateur
  only:
  - ops/deploy-k8s

###########################################
###         SEND URL TO GITHUB          ###
###########################################

#

.send_url_stage: &send_url_stage
  stage: "Send Url"
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - export DEPLOY_ID=$(cat github_deploy_id)
  - envsubst < k8s/scripts/send-url.sh > k8s/scripts/send-url-to-github.sh
  script:
  - sh k8s/scripts/send-url-to-github.sh $CI_COMMIT_REF_NAME

#

Send dev environment url to github:
  <<: *send_url_stage
  variables:
    URL: http://dila2sql-api.$CI_ENVIRONMENT_NAME.social.gouv.fr/
  environment:
    name: dev.factory
  except:
  - ops/deploy-k8s

Send prod environment url to github:
  <<: *send_url_stage
  variables:
    URL: https://dila2sql-api.$CI_ENVIRONMENT_NAME.social.gouv.fr/
  environment:
    name: incubateur
  only:
  - ops/deploy-k8s