---
dist: xenial
sudo: false
git:
  depth: 5

language: generic

_environments:
  - &docker_keys
    - secure: "e/DUn1ICMOGDY/h2ABVbhZFjThq4u/O6QUC1hF3QWBN3xhgoJa5VIxrSnH7joFR6It8/nc4Z49NVs3oFpbuWoqcZiPW/H/XxzbL8ATRUqagHacnXyjmpGcBH3YcmkleoGoqGfrlOn63y7OwOV2QuR+hvHQUEtbREBoSuFMfwqCVkRNfgoInYZPERx4JQSpWq1fjSSKwJ9Oe6bDCo7Ilu8mK2wH3cz+Jy1gye1qp1Gpay3O8WxesOpi4B3E/c8eCSXuZ6C1P3Bv7IJ5vOAPywu5fGoczismHA9gwwgyBqjjsbomy72KQa7215N3slZ1wzGJUk9yAtmoOhScZj2fCXYrwt1W4yDB6X7aOQILBb/7sFPRYzIKutwnQuzEK+yx2XjXeffQ7S79P1cB95EiAF46Yz+WsoXvK73h3UchKkAG0ZWA2qZlcCW1tyYnrhCSF2jw49Nqi8UTDM9aFzaNX9b2PfOyQlXpNpicPT/G4DoU/R5ZalNWWvQmd8ydjJY1rxtSC3xmgBMesWH9EQEqDiqiCRQIno5Qj7Ab46hStCaJyh8T7Uu2P63RqIL4/zvxA0IdvCrBpSi36o6GzP4nKBYDeK6QG5QfaT1gtM/WhmM7CHnkNR8U2MVUeSYZK+iGNGjgwAGnaWS5F9WhxmPHJh7jARmwX2ztZ+RZnsR5cJucE="
    - secure: "sbYGilLCu2p8lIiMsLTC9QLYxtxXSqjqeJfcaZL7jw0SwIiE8f7XlH+XitlATihX6LW7kEQCKy/GlZMSlz/vXoHHM+kFhfzrH9UNTtczeCOr5SbSs+ZpUVttJp+oNQ4AOhLpXFohqp6Vt40uLHWtehRLYE7KBMoU4xygMvvzzDubETFzc/U2/7BmlLd+QfZ5u72A8B/HZghElHKm2lkCkVRhu3gIuzelTx+vYAttIbjNQrl4X2BFVP51H90T5RLhdS1YuOLqv8YuyDrBjjM32gt8OhwO31zV8r2sdOnZ01tHZ6JvnDaa44KG+xMAgtoTy4DAypyUBXhLew2WwahJYUZJCPh+cutZ9kwz3S19RPmdy7GfSZnvprgts016/sE+y0CU7ozBN8J8lWaa/etxnyJMzvnA3nEsMeWrRZwVvYfQi134VTXAG/GTsOHUTXd31FFQojEepIEJzA6O5Y9cvGwGoR/gzGyT4u15nLx074BPUcfQ9u7R10HlSfFA0fmJc4hW09IhDBKCLeRFR0fI5/wyJySWTW3p0NCvDec520Ppk2KSx9/WoUr/iRkx6BqPz6qB+B9Qd3MTN0un4v1nifOcXbp9iFO69JMUV5HLo7VBXooL0bcW/OBMnxjaaHY7hCXSFwyfX8er12iTRsyJrWyasQAD74Fo/Ba0CwuZHls="
    
_steps:
  - &test_stage
    stage: Test
    language: python
    python: 3.7
    cache: pip
    before_script: pip install tox

  - &deploy_stage
    stage: Deploy
    if: type = push AND tag IS present
    script:
      - docker pull $DOCKER_IMAGE
      #
      - docker build -t $DOCKER_IMAGE:$TRAVIS_BRANCH $CONTEXT
      - docker build -t $DOCKER_IMAGE:latest $CONTEXT
      #
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push $DOCKER_IMAGE:$TRAVIS_BRANCH
      - docker push $DOCKER_IMAGE:latest

jobs:
  include:
    - <<: *test_stage
      name: Test
      script:
        - tox

    - <<: *deploy_stage
      name: Deploy latest image to Docker Hub
      env:
        - *docker_keys
        - DOCKER_IMAGE="socialgouv/legi.py"
        - CONTEXT=.
